### ISSUE TITLE
zipp version constraint does not match pyproject.toml

### ISSUE THREAD

**Issue by reggied** [conda-forge/importlib_metadata-feedstock#145]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

The `zipp` version required for versions 8.5.0 and above of `importlib_metadata` has been increased to version 3.20 in the [pyproject.toml](https://github.com/python/importlib_metadata/commit/56b61b3dd90df2dba2da445a8386029b54fdebf3) in the source repo. This in not reflected in the recipe/meta.yaml.

### Installed packages

```shell
importlib_metadata
zipp
```

### Environment info

```shell
importlib_metadata
zipp
```

**Comment by ocefpaf** [comment]
Just missed the opportunity to fix this in #146 . Do you want to send a PR to fix it?

**Comment by bollwyvl** [comment]
Was tidied up (only for `8.7.0`) in [#150](
https://github.com/conda-forge/importlib_metadata-feedstock/pull/150/files#diff-ad6aed43f0cf479348ccccec8e7185c4b70582192329f11908dd22a731771702R35).

Getting the pins right for historic versions would take a [repodata patches](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock) PR.

If that particular pin is problematic, could do something like:

```yaml
context:
  zipp_min: "3.20"

# ...

requirements:
  run:
    - zipp >=${{ zip_min }}

# ...

tests:
  - requirements:
      run:
        - zipp ${{ zip_min }}.*
        - pip
     script:
        - pip check  # duplicates the `python: pip_check` test, but 🤷 
```
